### ISSUE TITLE
Gulp v3.9.1 prevents successful start-up of the server

### ISSUE THREAD

**Issue by aharbuz** [donlion/mindpool-challenge#1]
An error occurred that prevented the dev server from successfully starting in my environment

It seems to be related to: 

https://stackoverflow.com/questions/35832739/error-with-gulp-serve-requiring-external-module-babel-register

Downgrading to Gulp v3.9.0 fixed the issue for me and created a new one.  Please see the other issue and reply if you my environment specs

**Comment by donlion** [comment]
Hey, @aharbuz.
I can run it without any issues locally, but I've added `babel-cli` to make sure you can too :) Thanks
