### ISSUE TITLE
Error: Cannot find module './tools/unusedFiles'

### ISSUE THREAD

**Issue by aharbuz** [donlion/mindpool-challenge#2]
After fixing issue #1 another error occurred when trying to start the development server:

Error: Cannot find module './tools/unusedFiles'
in gulpfile.babel.js

Removing the references in that file allowed the dev server to successfully start

Please reply if you need my environment specs.

**Comment by donlion** [comment]
The `unused-files` script shouldn't run unless you do so specifically.
I've removed it anyways, since it's not part of this repository - I forgot to remove the reference in `package.json`
Thanks 👍
